version: "3.9"

services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    restart: always
    ports:
      - "${NAVIDROME_PORT}:${NAVIDROME_PORT}"
    volumes:
      - navidrome_data:/data
    environment:
      - ND_SCANSCHEDULE=@every 5m
      - ND_MUSICFOLDER=/music
    env_file:
      - .env

volumes:
  navidrome_data:
